name = "sahayakbooks-api"
main = "src/index.ts"
compatibility_date = "2026-09-23"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "sahayakbooks-production"
database_id = "13ea1d62-ab1e-4091-b6da-d80d70a45fc0"
migrations_dir = "../migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sahayakbooks-media"
